# Generated by Django 3.2 on 2021-07-10 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_celleraccount'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('image', models.ImageField(upload_to='product/', verbose_name='Image')),
                ('price', models.PositiveSmallIntegerField(default=0, verbose_name='Price')),
                ('description', models.TextField(verbose_name='Description')),
                ('views', models.PositiveSmallIntegerField(default=0, verbose_name='Views')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('celler_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='account.celleraccount')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='home.subcategory')),
            ],
        ),
    ]
