# Generated by Django 3.2 on 2021-07-10 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('account', '0002_auto_20210710_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('phone', models.CharField(max_length=24, verbose_name='Phone')),
                ('image', models.ImageField(blank=True, upload_to='celler_account/', verbose_name='Image')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('celler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celler_account', to='account.celler')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celler_accounts', to='home.subcategory')),
            ],
        ),
    ]
